[Fix] Package upgrades (#172)
* Fix some configuration :bug:s

* Eliminates unneeded (apparently) script

Since build is done independently by rollup, this does not seem to be needed as long as you run npm run build before you run `npm run storybook`. (Although TBH I haven't seen where those SVGs are used)

Besides, this errors with:

```
/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:151
        base = Object.assign(new Error(base.message), base);
                             ^

Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:151:30)
    at Module.error (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:10020:16)
    at Module.tryParse (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:10423:25)
    at Module.setSource (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:10326:24)
    at ModuleLoader.addModuleSource (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:19687:20)
    at async ModuleLoader.fetchModule (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:19743:9)
    at async Promise.all (index 6)
    at async ModuleLoader.fetchStaticDependencies (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:19769:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:19745:9) {
  code: 'PARSE_ERROR',
  parserError: SyntaxError: Unexpected token (1:0)
      at Parser.pp$4.raise (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:16935:13)
      at Parser.pp.unexpected (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:14443:8)
      at Parser.pp$3.parseExprAtom (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:16312:10)
      at Parser.pp$3.parseExprSubscripts (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:16107:19)
      at Parser.pp$3.parseMaybeUnary (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:16073:17)
      at Parser.pp$3.parseExprOps (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:16006:19)
      at Parser.pp$3.parseMaybeConditional (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:15989:19)
      at Parser.pp$3.parseMaybeAssign (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:15957:19)
      at Parser.pp$3.parseExpression (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:15921:19)
      at Parser.pp$1.parseStatement (/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/node_modules/rollup/dist/shared/rollup.js:14633:45) {
    pos: 0,
    loc: Position { line: 1, column: 0 },
    raisedAt: 1
  },
  id: '/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/src/static/images/icons/clear-search-dark.svg',
  pos: 0,
  loc: {
    column: 0,
    file: '/home/jmerelo/progs/polypoly/polyPod/core/utils/poly-look/src/static/images/icons/clear-search-dark.svg',
    line: 1
  },
  frame: '1: <svg width="14" height="13" viewBox="0 0 14 13" fill="none" xmlns="http://www.w3.org/2000/svg">\n' +
    '   ^\n' +
    '2: <path d="M8.28906 6.5L12.3125 2.51562L13.1328 1.69531C13.25 1.57812 13.25 1.38281 13.1328 1.22656L12.2734 0.367188C12.1172 0.25 11.9219 0.25 11.8047 0.367188L7 5.21094L2.15625 0.367188C2.03906 0.25 1.84375 0.25 1.6875 0.367188L0.828125 1.22656C0.710938 1.38281 0.710938 1.57812 0.828125 1.69531L5.67188 6.5L0.828125 11.3438C0.710938 11.4609 0.710938 11.6562 0.828125 11.8125L1.6875 12.6719C1.84375 12.7891 2.03906 12.7891 2.15625 12.6719L7 7.82812L10.9844 11.8516L11.8047 12.6719C11.9219 12.7891 12.1172 12.7891 12.2734 12.6719L13.1328 11.8125C13.25 11.6562 13.25 11.4609 13.1328 11.3438L8.28906 6.5Z" fill="#0F1938"/>\n' +
    '3: </svg>',
```

* :pencil2: :bug:

* :rotating_light: